spin_manifest_version = "1"
authors = ["Jeremy Rickard <jeremyrrickard@gmail.com>"]
description = "Hello from kubecon"
name = "kubecon-hello"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "kubecon-hello"
source = "main.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/..."
[component.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
